# ---------------------------------------- #
# Test macro file for Gamma Spectroscopy
# ---------------------------------------- #

# Set verbose levels
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# Print progress handled automatically

# Initialize
/run/initialize

# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

# Set analogue decay mode
/process/had/rdm/analogueMC 1

# Set ion
/gun/particle ion
/gun/ion 27 60

/analysis/setFileName co60_an

# Run events
/run/beamOn 1000000


# Set variance reduction decay mode with time profile
/process/had/rdm/decayBiasProfile measures.data
/process/had/rdm/analogueMC 0

/analysis/setFileName co60_vr

# Run events
/run/beamOn 1000000