# Macro file for visualization initialization
# This is run automatically when starting in interactive mode

# Initialize kernel
/run/initialize

# Open viewer
/vis/open

# Disable auto refresh
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry
/vis/drawVolume

# Set camera position (view from side)
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/lightsVector -1 0 0

# Set zoom and style
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw coordinate axes (5 cm length)
/vis/scene/add/axes 0 0 0 5 cm

# To draw particle trajectories (when you run events)
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 6

# Draw hits at end of event
/vis/scene/add/hits

# Make the World box invisible
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility EncasementMother 0 false
/vis/geometry/set/visibility CupMother 0 false
/vis/geometry/set/visibility GeMother 0 false
/vis/geometry/set/visibility AbsorberAssembly 0 false

# Add color to volumes (depth, r, g, b, alpha)
/vis/viewer/set/background white
/vis/geometry/set/colour EncasementCap 0 0.75 0.75 0.75 0.5
/vis/geometry/set/colour EncasementWall 0 0.75 0.75 0.75 0.5
/vis/geometry/set/colour Cup 0 0.75 0.75 0.75 0.5
/vis/geometry/set/colour CupCapAl 0 0.75 0.75 0.75 0.5
/vis/geometry/set/colour CupCapMylar 0 0.90 0.90 0.90 0.5
/vis/geometry/set/colour CupBackCap 0 0.75 0.75 0.75 0.5
/vis/geometry/set/colour DeadLayerFront 0 0.65 0.60 0.35 0.5
/vis/geometry/set/colour DeadLayerSide 0 0.65 0.60 0.35 0.5
/vis/geometry/set/colour HPGE_LV_1 0 0.75 0.65 0.55 0.5
/vis/geometry/set/colour HPGE_LV_2 0 0.75 0.65 0.55 0.5
/vis/geometry/set/colour DeadLayerBoreBottom 0 0.65 0.60 0.35 0.5
/vis/geometry/set/colour DeadLayerBoreWall 0 0.65 0.60 0.35 0.5

/vis/geometry/set/colour Absorber 0 0.60 0.60 0.60 1.0
/vis/geometry/set/colour GoldFrontFoil 0 1 0.8 0 0.5
/vis/geometry/set/colour GoldBackFoil 0 1 0.8 0 0.5

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
