# Macro file for visualization initialization
# This is run automatically when starting in interactive mode

# Initialize kernel
/run/initialize

# Open viewer
/vis/open

# Disable auto refresh
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry
/vis/drawVolume

# Set camera position (view from side)
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/lightsVector -1 0 0

# Set zoom and style
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw coordinate axes (5 cm length)
/vis/scene/add/axes 0 0 0 5 cm

# To draw particle trajectories (when you run events)
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 6

# Draw hits at end of event
/vis/scene/add/hits


# Make the World box, mother volumes, and vacuums invisible
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility DetectorMother_1 0 false
/vis/geometry/set/visibility DetectorMother_2 0 false
/vis/geometry/set/visibility AbsorberAssembly 0 false
/vis/geometry/set/visibility Vacuum1 0 false
/vis/geometry/set/visibility Vacuum2 0 false
/vis/geometry/set/visibility CentralContact 0 false


# Add color to volumes (depth, r, g, b, alpha)
/vis/viewer/set/background white

/vis/geometry/set/colour Absorber 0 0.60 0.60 0.60 0.75
/vis/geometry/set/colour GoldFrontFoil 0 0.85 0.75 0.35 0.5
/vis/geometry/set/colour GoldBackFoil 0 0.85 0.75 0.35 0.5

#/vis/geometry/set/colour Cryostat 0 0.45 0.55 0.75 0.5
#/vis/geometry/set/colour DetectorCup 0 0.45 0.55 0.75 0.5

/vis/geometry/set/colour Cryostat 0 0.40 0.40 0.40 0.5
/vis/geometry/set/colour DetectorCup 0 0.40 0.40 0.40 0.5

/vis/geometry/set/colour ActiveCrystal 0 0.50 0.70 0.50 0.5

/vis/geometry/set/colour OuterDeadLayer 0 0.55 0.40 0.60 0.5
/vis/geometry/set/colour InnerDeadLayer 0 0.55 0.40 0.60 0.5


# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
