# ---------------------------------------- #
# Macro file for TOF measurements
#
# Places detector between an initial and
#   and final angle in steps and creates
#   individuals runs of SimLiT-generated
#   neutrons for TOF measurements
#
# Detector angle and event gen handled by
#   angles.mac
# ---------------------------------------- #

# Set verbose levels
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# Print progress handled automatically

# Initialize
/run/initialize

# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

# Set parameters
/neutronTOF/gun/useSimLiT true
/neutronTOF/gun/exposureTime 900 s
/neutronTOF/det/setWorldMaterial air
/neutronTOF/det/setDetectorDistance 25 cm

/analysis/h1/set 3 100 0 900 s
/analysis/setFileName Activation_1

# Run events
/run/beamOn 1000000
